library(Seurat)
library(Matrix)
library(data.table)
library(ggplot2)
library(tidyverse)
library(parallel)
library(pheatmap)
library(dplyr)

#Read the data into the environment####
soybean.list <- list()
for (i in c('N','R')){
  #The path where the result is generated by cellranger
  data_dir = paste0(i,'/outs/filtered_feature_bc_matrix')
  expression_matrix <- Read10X(data.dir=data_dir, gene.column = 1, unique.features = TRUE,
                               strip.suffix = FALSE)
  colnames(expression_matrix) <- gsub('-1',paste0('-',i),colnames(expression_matrix))
  soybean.list[[i]] <- CreateSeuratObject(counts = expression_matrix)
}
#Normalization, dimensionality reduction and cell clustering####
soybean.combined <- merge(soybean.list[['N']], y = soybean.list[['R']], add.cell.ids = c("N", "R"))
soybean.combined <- SCTransform(soybean.combined, verbose = T, variable.features.n = 3000)
soybean.combined <- RunPCA(object = soybean.combined, verbose = FALSE, npcs = 30)
soybean.combined <- RunUMAP(object = soybean.combined, dims = 1:30, 
                            min.dist = 0.5, n.neighbors = 30, seed.use = 100)
head(soybean.combined@meta.data)
soybean.combined@meta.data$sample <- substr(rownames(soybean.combined@meta.data),1,1)
DimPlot(soybean.combined, reduction = "umap", label = T)
DefaultAssay(soybean.combined) <- 'RNA'
soybean.combined <- NormalizeData(soybean.combined, normalization.method = "LogNormalize",
                                  scale.factor = 1e6)
DefaultAssay(soybean.combined) <- 'SCT'
soybean.combined <- FindNeighbors(soybean.combined,reduction = 'pca',dims = 1:30)
soybean.combined <- FindClusters(soybean.combined, resolution = 0.3)
DimPlot(soybean.combined, reduction = "umap",group.by = 'seurat_clusters',label = T)